version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-replica
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
